services:
  db:
    image: postgres
    restart: always
    environment:
      # NOT RECOMMENDED for a production environment. Trusts all incomming
      # connections.
      POSTGRES_HOST_AUTH_METHOD: trust
      
  opa:
    image: openpolicyagent/opa
    command: 
      - "run" 
      - "--disable-telemetry"
      - "--server"
      # - "--v1-compatible" 
      - "--config-file=/opa-config.yaml"
      - "/policies"
    ports:
      - 8181:8181
    volumes:
      - ./plugins/opa/policies:/policies
      - ./plugins/opa/opa-config.yaml:/opa-config.yaml